# Generated by Django 4.0.1 on 2022-01-31 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_alter_cadastro_valor_projeto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='data_inicio',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='data_termino',
            field=models.DateField(),
        ),
    ]
