# Generated by Django 4.0.1 on 2022-01-31 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0004_alter_cadastro_data_inicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='data_inicio',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='data_termino',
            field=models.IntegerField(),
        ),
    ]
